# ??? ?????? ?? ??
spring.application.name=mvc-github-login
# ?? ?? ?? ??
server.port=8081

# ???? ??? ?? ???? (?? ?? ?? ??)
spring.thymeleaf.cache=false
# ???? ??? ?? ??? ??
spring.thymeleaf.encoding=UTF-8

# ??? ??/?? ?? ??? ??
server.servlet.encoding.charset=UTF-8
# ?? ??/??? UTF-8 ??? ?? ??
server.servlet.encoding.force=true

# Oracle ?? ??
spring.datasource.url=jdbc:oracle:thin:@project-db-campus.smhrd.com:1524:xe?oracle.jdbc.defaultNChar=true
spring.datasource.username=campus_24KDT_LI8_p2_1
spring.datasource.password=smhrd1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ?? ?? ????? ??? ?? API ??
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


mybatis.type-aliases-package=com.project.mvcgithublogin.domain
mybatis.mapper-locations=classpath:/mapper/*.xml

app.google.client-id=${spring.security.oauth2.client.registration.google.client-id}
