spring.application.name=join
# Oracle ?? ??
server.port=${JOIN_SERVER_PORT:8081}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${JOIN_DB_URL:jdbc:oracle:thin:@project-db-campus.smhrd.com:1524:xe}
spring.datasource.username=${JOIN_DB_USERNAME:campus_24KDT_LI8_p2_1}
spring.datasource.password=${JOIN_DB_PASSWORD:smhrd1}

# JPA ?? (?? ???? ???? none ?? update)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
