spring.application.name=mvc-github-login
server.port=8081

spring.thymeleaf.cache=false

spring.datasource.url=jdbc:oracle:thin:@project-db-campus.smhrd.com:1524:xe
spring.datasource.username=campus_24KDT_LI8_p2_1
spring.datasource.password=smhrd1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

mybatis.type-aliases-package=com.project.mvcgithublogin.domain
mybatis.mapper-locations=classpath:/mapper/UserMapper.html
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
