# -*- coding: utf-8 -*-
"""최종 발화분석 파이프라인.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xg6hUee8Xg61B6E4zJmrly6vdF1lyZ-w
"""

import os
import re
from pathlib import Path

import torch
import librosa
import numpy as np
from transformers import pipeline
from openai import OpenAI

# STT 모델 로드

MODEL_NAME = "seastar105/whisper-medium-komixv2"

device = 0 if torch.cuda.is_available() else -1

asr = pipeline(
    "automatic-speech-recognition",
    model=MODEL_NAME,
    device=device,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
)

print("device:", device)

# STT 실행

def transcribe_audio(audio_path):
    """
    음성 파일 경로를 받아 STT 텍스트를 반환한다.
    """

    audio_array, sampling_rate = librosa.load(
        str(audio_path),
        sr=16000,
        mono=True
    )

    result = asr(
        {
            "array": audio_array,
            "sampling_rate": sampling_rate
        },
        generate_kwargs={
            "language": "ko",
            "task": "transcribe"
        }
    )

    return result["text"].strip()

# STT 텍스트 전처리

def preprocess_stt_text(text):
    """
    STT 결과를 분석용으로 최소 전처리한다.
    의미를 바꾸는 수정은 하지 않는다.
    """

    if text is None:
        return ""

    text = str(text).strip()

    # 라벨/비언어 표기 제거
    text = re.sub(r"\((NO:|웃음|기침|잡음|소음|침묵|무음|음악)\)", " ", text)
    text = re.sub(r"\[(NO:|웃음|기침|잡음|소음|침묵|무음|음악)\]", " ", text)
    text = re.sub(r"<(NO:|웃음|기침|잡음|소음|침묵|무음|음악)>", " ", text)

    # 괄호 없이 NO:가 들어오는 경우
    text = re.sub(r"\bNO:\s*", " ", text)

    # 줄바꿈, 탭, 여러 공백 정리
    text = re.sub(r"\s+", " ", text)

    # 양끝 따옴표 제거
    text = text.strip(" \"'“”‘’")

    return text.strip()

# 반응 시간 측정 - 첫 소리 감지

def detect_first_sound_time(
    audio_path,
    sample_rate=16000,
    frame_duration=0.05,
    threshold_ratio=0.10,
    min_sound_duration=0.15
):
    """
    wav 파일 앞부분에서 처음 소리가 감지되는 시점을 초 단위로 반환한다.

    audio_path: 음성 파일 경로
    sample_rate: 음성 샘플레이트
    frame_duration: 소리 크기를 확인할 구간 길이(초)
    threshold_ratio: 전체 최대 소리 크기 대비 기준 비율
    min_sound_duration: 소리가 이 시간 이상 이어져야 실제 소리로 인정
    """

    y, sr = librosa.load(audio_path, sr=sample_rate, mono=True)

    if len(y) == 0:
        return None

    frame_length = int(sr * frame_duration)
    min_sound_frames = max(1, int(min_sound_duration / frame_duration))

    max_amplitude = np.max(np.abs(y))

    if max_amplitude == 0:
        return None

    threshold = max_amplitude * threshold_ratio

    sound_flags = []

    for start in range(0, len(y), frame_length):
        frame = y[start:start + frame_length]

        if len(frame) == 0:
            continue

        frame_amplitude = np.mean(np.abs(frame))
        is_sound = frame_amplitude >= threshold
        sound_flags.append(is_sound)

    consecutive = 0

    for i, is_sound in enumerate(sound_flags):
        if is_sound:
            consecutive += 1

            if consecutive >= min_sound_frames:
                first_frame_index = i - min_sound_frames + 1
                first_sound_time = first_frame_index * frame_duration
                return round(first_sound_time, 2)
        else:
            consecutive = 0

    return None

def calculate_response_time_from_audio(audio_path):
    """
    음성 파일에서 첫 소리 감지 시점을 반응 시간으로 사용한다.
    """

    return detect_first_sound_time(audio_path)

# 반복어 비율 계산

def tokenize_text(text):
    """
    STT 텍스트를 공백 기준 어절로 분리한다.
    문장부호는 반복어 계산에 방해되므로 제거한다.
    """

    if text is None:
        return []

    text = str(text).strip()

    if text == "":
        return []

    # 문장부호 제거
    text = re.sub(r"[.,!?。！？…~]+", " ", text)

    # 괄호, 따옴표 등 제거
    text = re.sub(r"[\"'“”‘’()\[\]{}<>]", " ", text)

    # 여러 공백 정리
    text = re.sub(r"\s+", " ", text).strip()

    if text == "":
        return []

    return text.split(" ")


def calculate_repetition_ratio(text):
    """
    연속 반복 어절 비율을 계산한다.
    반환값은 퍼센트(%) 단위 float.
    """

    tokens = tokenize_text(text)

    if len(tokens) == 0:
        return 0.0

    repeated_count = 0

    for i in range(1, len(tokens)):
        if tokens[i] == tokens[i - 1]:
            repeated_count += 1

    ratio = repeated_count / len(tokens) * 100

    return round(ratio, 2)


def score_repetition_ratio(repetition_ratio):
    """
    반복어 비율을 0~100점으로 변환한다.
    낮을수록 좋은 점수다.
    """

    if repetition_ratio is None:
        return 0

    if repetition_ratio <= 5:
        return 100
    elif repetition_ratio <= 15:
        return 80
    elif repetition_ratio <= 30:
        return 60
    elif repetition_ratio <= 50:
        return 40
    else:
        return 0


def analyze_repetition(text):
    """
    STT 텍스트에서 반복어 비율과 반복어 점수를 함께 계산한다.
    """

    repetition_ratio = calculate_repetition_ratio(text)
    repetition_score = score_repetition_ratio(repetition_ratio)

    return {
        "repetition_ratio": repetition_ratio,
        "repetition_score": repetition_score
    }

# 평균 문장 길이 계산

# 평균 문장 길이 계산에서 제거할 단독 채움 표현
FILLER_WORDS_FOR_LENGTH = {
    "어어", "어어어",
    "음", "음음", "으음", "으으음",
    "에", "에에",
    "흠", "흐음"
}


# 평균 문장 길이 계산에서 제거할 구 단위 채움 표현
FILLER_PHRASES_FOR_LENGTH = {
    "그 뭐냐",
    "그 뭐지",
    "그 뭐더라",
    "그 뭐였더라",
    "어 뭐냐",
    "어 뭐지",
    "어 뭐더라",
    "음 뭐냐",
    "음 뭐지",
    "음 뭐더라",
    "뭐라고 해야 되나",
    "뭐라고 해야 하나",
    "뭐라 해야 되나",
    "뭐라 해야 하나",
    "뭐라고 그러지",
    "뭐라 그러지",
    "그 뭐시냐",
    "그 머시냐",
    "그 뭐시더라",
    "그 머시더라",
    "뭐시더라",
    "머시더라",
}


def remove_filler_phrases_for_length(text):
    """
    평균 문장 길이 계산용으로 구 단위 채움 표현을 제거한다.
    예: '그 뭐냐', '뭐라고 해야 하나'
    """

    if text is None:
        return ""

    text = str(text)

    # 긴 표현부터 제거해야 짧은 표현과 충돌이 덜 난다.
    phrases = sorted(FILLER_PHRASES_FOR_LENGTH, key=len, reverse=True)

    for phrase in phrases:
        text = text.replace(phrase, " ")

    text = re.sub(r"\s+", " ", text).strip()

    return text


def remove_filler_words_for_length(text):
    """
    평균 문장 길이 계산용으로 단독 채움 표현을 제거한다.
    '어', '음' 등이 독립된 토큰일 때만 제거한다.
    """

    if text is None:
        return ""

    text = str(text).strip()

    if text == "":
        return ""

    tokens = text.split()
    kept_tokens = []

    for token in tokens:
        # 양끝 문장부호만 제거해서 비교한다.
        # 예: '어,' → '어'
        clean_token = re.sub(r"^[.,!?。！？…~\"'“”‘’()\[\]{}<>]+", "", token)
        clean_token = re.sub(r"[.,!?。！？…~\"'“”‘’()\[\]{}<>]+$", "", clean_token)

        if clean_token in FILLER_WORDS_FOR_LENGTH:
            continue

        kept_tokens.append(token)

    return " ".join(kept_tokens)


def remove_fillers_for_length(text):
    """
    평균 문장 길이 계산용으로만 채움 표현을 제거한다.
    원본 STT나 preprocessed_text 자체를 바꾸는 용도가 아니다.
    """

    text = remove_filler_phrases_for_length(text)
    text = remove_filler_words_for_length(text)

    text = re.sub(r"\s+", " ", text).strip()

    return text


def count_meaningful_chars(text):
    """
    답변 전체 의미 글자 수를 계산한다.
    공백과 문장부호를 제외한다.
    """

    if text is None:
        return 0

    text = str(text)

    # 공백 제거
    text = re.sub(r"\s+", "", text)

    # 문장부호 및 괄호류 제거
    text = re.sub(r"[.,!?。！？…~\"'“”‘’()\[\]{}<>]", "", text)

    return len(text)


def calculate_answer_length(text):
    """
    답변 전체 의미 글자 수를 계산한다.
    기존 avg_sentence_length 컬럼에 저장하더라도,
    실제 의미는 '답변 전체 의미 글자 수'로 정의한다.
    """

    if text is None:
        return 0.0

    text = str(text).strip()

    if text == "":
        return 0.0

    cleaned_text = remove_fillers_for_length(text)
    char_count = count_meaningful_chars(cleaned_text)

    return float(char_count)


def score_answer_length(answer_length, question_type_name):
    """
    답변 전체 의미 글자 수를 0~100점으로 변환한다.
    answer_length: 채움 표현, 공백, 문장부호를 제외한 글자 수
    """

    if answer_length is None or answer_length <= 0:
        return 0

    # 오늘 날짜 말하기는 짧게 답해도 정상.
    # 길이는 최종 점수에 반영하지 않거나, 발화 존재 여부만 본다.
    if question_type_name == "오늘 날짜 말하기":
        return 100

    # 공통점 말하기는 짧아도 정답일 수 있음.
    # 예: 둘 다 과일이에요 → 7글자
    if question_type_name == "규칙 기반 언어추론":
        if answer_length >= 6:
            return 100
        elif answer_length >= 3:
            return 80
        elif answer_length >= 1:
            return 60
        else:
            return 0

    # 상황 질문은 행동이 드러나면 짧아도 가능.
    # 예: 119를 불러요 → 6~7글자
    if question_type_name == "상황 질문 답하기":
        if answer_length >= 10:
            return 100
        elif answer_length >= 6:
            return 80
        elif answer_length >= 3:
            return 60
        elif answer_length >= 1:
            return 40
        else:
            return 0

    # 그림 설명은 여러 요소를 묘사해야 하므로 조금 더 긴 발화가 자연스러움.
    if question_type_name == "그림 설명하기":
        if answer_length >= 25:
            return 100
        elif answer_length >= 15:
            return 80
        elif answer_length >= 6:
            return 60
        elif answer_length >= 1:
            return 40
        else:
            return 0

    # 추억 말하기는 구체적 회상이 필요하므로 가장 길이 기준을 높게 둔다.
    if question_type_name == "추억 말하기":
        if answer_length >= 30:
            return 100
        elif answer_length >= 18:
            return 80
        elif answer_length >= 8:
            return 60
        elif answer_length >= 1:
            return 40
        else:
            return 0

    return 0


def analyze_answer_length(text, question_type_name):
    """
    답변 전체 의미 글자 수와 길이 점수를 함께 계산한다.
    """

    answer_length = calculate_answer_length(text)
    answer_length_score = score_answer_length(answer_length, question_type_name)

    return {
        "avg_sentence_length": answer_length,  # DB 컬럼명이 avg_sentence_length라면 여기에 저장
        "sentence_length_score": answer_length_score
    }

# LLM 모델 불러오기

API_KEY = os.getenv("OPENAI_API_KEY")
client = OpenAI(api_key=API_KEY) if API_KEY else None

LLM_MODEL_NAME = "gpt-5.4-mini-2026-03-17"

VALID_SCORES = {0, 40, 60, 80, 100}

#@title 화행 적절성 점수 채점 프롬프트

APPROPRIATENESS_PROMPTS = {
    "오늘 날짜 말하기": """
당신은 노인 인지검사의 화행 적절성 채점자다. 아래 문항에 대한 수급자의 음성 답변(STT 변환 텍스트)을 평가한다.

[이 유형의 문항 의도]
현재 날짜, 시간, 요일, 계절, 상대적 시간 정보를 말하도록 요구하는 문항이다. 이 평가는 날짜의 실제 정답 여부를 평가하는 것이 아니라, 문항이 요구한 시간·날짜 요소를 답변이 충족했는지를 평가한다.

[문항]
{question_text}

[답변]
{stt_text}

[평가 규칙]

* 평가 대상은 "답변이 문항이 요구한 시간·날짜 요소를 충족했는가"이다.
* 날짜의 실제 사실 정확성은 평가하지 않는다.
* 발음, 문법, 띄어쓰기, 존댓말 여부는 평가하지 않는다.
* 먼저 [문항]을 읽고, 문항이 요구하는 시간·날짜 요소를 빠짐없이 나눈다.
* 요구 요소에는 연도, 월, 일, 요일, 계절뿐 아니라 오전/오후, 오늘/내일/어제, 며칠 뒤/며칠 전, 주말까지 남은 날 수처럼 문항이 직접 요구한 시간 관련 정보도 포함한다.
* 문항이 여러 요소를 요구하면 각 요소를 따로 세어야 한다.
* 답변이 요구 요소 중 하나만 충족했다고 해서 100점으로 평가하지 않는다.
* 문항이 요구하지 않은 요소가 빠졌다는 이유로 감점하지 않는다.
* 답변이 비었거나 침묵뿐이면 0점이다.
* 답변이 "모른다", "몰라", "내가 어떻게 알아"처럼 시간·날짜 정보를 제공하지 않으면 0점이다.
* 문항과 전혀 무관한 답변이면 0점이다.
* 시간·날짜와 관련된 표현이지만 문항이 요구한 구체 요소를 충족하지 못한 경우는 40점으로 평가한다. 예: 요일을 물었는데 "평일"이라고 답함, 월을 물었는데 "여름"이라고 답함.
* 문항이 "요일"을 요구하는 경우, 월요일·화요일·수요일·목요일·금요일·토요일·일요일처럼 구체적인 요일명을 답해야 해당 요구 요소를 충족한 것으로 본다.
* "평일", "주말", "쉬는 날", "일하는 날"처럼 요일의 범주나 성격만 말한 경우는 구체적인 요일을 답한 것이 아니므로 요일 요구 요소를 충족하지 못한 것으로 본다.
* 단, 문항이 "평일인지 주말인지"를 물은 경우에는 "평일", "주말"을 요구 요소 충족으로 인정한다.
* 문항이 "며칠", "몇 일", "오늘은 며칠"처럼 일자를 요구하는 경우, 답변의 숫자 표현을 일자로 해석할 수 있으면 요구 요소를 충족한 것으로 본다.
* STT 변환 특성상 "이일", "삼일", "사일", "십오일", "이십일일"처럼 숫자와 '일'이 붙어 있거나 띄어쓰기가 불완전해도 일자 표현으로 인정한다.
* 답변이 문항의 요구 요소와 자연스럽게 연결되면, 표기 혼동 가능성만으로 0점 처리하지 않는다.
* 예를 들어 문항이 "오늘은 며칠인가요?"이고 답변이 "이일"이면 "2일"을 답한 것으로 보고 100점으로 평가한다.

[요구 요소 판별 보충 규칙]
- 문항이 요구하는 요소는 문항의 표현을 기준으로 따로 나누어 센다.
- "몇 월 며칠"은 하나의 요소가 아니라 "월"과 "일" 두 요소이다.
- "팔월 이십일", "유월 사일", "8월 21일"처럼 월과 일이 함께 나온 답변은 월 요소와 일 요소를 각각 충족한 것으로 본다.
- "연도와 월, 일", "몇 년 몇 월 며칠", "월, 일, 요일"처럼 나열된 항목은 각각 별도의 요구 요소로 본다.
- "오전인지 오후인지", "평일인지 주말인지", "다음 달", "내일 요일", "며칠 뒤가 주말인지"처럼 문항이 직접 요구한 상대적·생활형 시간 정보도 별도의 요구 요소로 본다.
- 문항이 구체적 요일명을 요구하는 경우, "평일", "주말", "쉬는 날"은 구체적 요일을 답한 것이 아니므로 요일 요소를 충족하지 못한 것으로 본다.
- 단, 문항이 "평일인지 주말인지"를 직접 요구하는 경우에는 "평일", "주말"을 해당 요구 요소 충족으로 인정한다.

[채점 절차]
반드시 다음 순서로 판단한다.

1. [문항]에서 요구 요소를 모두 찾는다.
   예: "오늘이 몇 월 며칠인지, 그리고 오전인지 오후인지 말씀해 주세요."
   → 요구 요소는 "월", "일", "오전/오후"이다. 총 3개이다.

2. [답변]에서 실제로 충족한 요소만 찾는다.
   예: "오후"
   → 충족한 요소는 "오전/오후" 1개뿐이다. "월"과 "일"은 충족하지 못했다.

3. 요구 요소 개수와 충족 요소 개수를 비교해 점수를 정한다.

[점수 기준]

* 100: 문항이 요구한 시간·날짜 요소를 모두 분명히 답함.
* 80: 요구 요소 대부분을 답했으나 일부가 빠졌거나, 한 요소가 불확실함.
* 60: 요구 요소 중 일부만 답했거나, 절반 이하만 분명히 답함.
* 40: 시간·날짜와 관련은 있으나 문항이 요구한 요소를 거의 충족하지 못함.
* 0: 무응답, 침묵, 모름/거부, 알아들을 수 없음, 문항과 무관함.

[생활형·추론형 문항 보충 규칙]
- 문항이 "오늘 날짜/현재 날짜/오늘 요일/이번 달" 같은 기본 시간 요소와 "다음 달", "내일 요일", "며칠 뒤가 주말인지", "평일/주말 여부" 같은 부가·추론 요소를 함께 요구하는 경우가 있다.
- 이런 문항에서 기본 시간 요소를 분명히 답했지만 부가·추론 요소만 빠진 경우는 80점으로 평가한다.
- 반대로 부가·추론 요소만 답하고 기본 시간 요소를 답하지 않은 경우는 60점으로 평가한다.
- 기본 요소와 부가 요소를 모두 답하면 100점이다.

[요구 요소 개수별 기준]

- 요구 요소가 1개인 경우:
  - 요구 요소를 분명히 답하면 100점.
  - 요구 요소를 불확실하게 답하면 60점.
  - 요구 요소를 답하지 못하면 0점.
  - 시간·날짜와 관련은 있으나 요구 요소를 충족하지 못하면 40점.

- 요구 요소가 2개인 경우:
  - 2개를 모두 답하면 100점.
  - 1개만 답한 경우는 아래 기준으로 나눈다.
    1) 기본 날짜·시간 요소를 분명히 답하고 부가 요소만 빠졌으면 80점.
    2) 부가 요소만 답하고 기본 날짜·시간 요소가 빠졌으면 60점.
    3) 두 요소의 중요도 차이가 없고 1개만 답했으면 60점.
  - 시간·날짜 관련 말은 있으나 요구 요소를 충족하지 못하면 40점.
  - 0개를 답하거나 모른다고 하면 0점.

- 요구 요소가 3개인 경우:
  - 3개를 모두 답하면 100점.
  - 2개를 분명히 답하면 80점.
  - 1개만 답하면 60점.
  - 시간·날짜 관련 말은 있으나 요구 요소를 충족하지 못하면 40점.
  - 0개를 답하거나 모른다고 하면 0점.

- 요구 요소가 4개 이상인 경우:
  - 모두 답하면 100점.
  - 1개만 빠지고 나머지를 답하면 80점.
  - 절반 정도 또는 절반 이하만 답하면 60점.
  - 시간·날짜 관련 말은 있으나 요구 요소를 거의 충족하지 못하면 40점.
  - 0개를 답하거나 모른다고 하면 0점.

[추가 경계 규칙]
- "팔월 이십일", "유월 사일", "8월 21일"처럼 월과 일이 붙어 있는 표현은 반드시 월 요소 1개와 일 요소 1개를 각각 충족한 것으로 센다. 절대 하나의 날짜 요소로만 세지 않는다.
- 요구 요소가 3개이고 답변이 그중 2개를 충족하면 80점으로 평가한다.
- 요구 요소가 4개이고 답변이 그중 3개를 충족하면 80점으로 평가한다.

- 생활형·추론형 문항에서 현재 날짜, 현재 요일, 현재 월처럼 기준이 되는 기본 요소를 답했고, 다음 달, 내일 요일, 주말까지 남은 날 수, 평일/주말 여부 같은 부가 요소만 빠진 경우는 80점으로 평가한다.
- 반대로 부가 요소만 답하고 기본 요소가 빠진 경우는 60점으로 평가한다.

- 문항에 나온 단어를 사용했더라도, 요구 요소의 값을 답하지 않으면 충족으로 보지 않는다.
- "주말은 곧 오겠죠", "내일은 내일이지"처럼 문항의 단어를 반복하거나 일반적인 반응만 말하고, 며칠 뒤인지·무슨 요일인지 같은 요구 요소의 값을 답하지 않으면 40점으로 평가한다.

- "아침 먹었어요", "밥 먹었어요", "날씨가 좋아요", "기분이 좋아요"처럼 일상 활동, 식사, 날씨, 기분에 대한 말은 문항이 요구한 시간·날짜 요소와 무관하면 0점으로 평가한다.
- 특히 "오전/오후"를 묻는 문항에서 "아침 먹었어요"처럼 식사 경험을 말한 것은 오전/오후를 직접 답한 것이 아니므로 0점으로 평가한다.

- 요구 요소에 대해 두 개 이상의 후보를 말하며 헷갈린다고 한 경우, 해당 요소를 불확실하게 시도한 것으로 보고 60점 평가에 반영한다.
- 단, 요구 요소가 여러 개인데 한 요소만 불확실하게 답하고 나머지를 답하지 못한 경우는 60점을 넘지 않는다.

[주의할 예시]

* 문항: "오늘이 몇 월 며칠인지, 그리고 오전인지 오후인지 말씀해 주세요."
  답변: "오후"
  판단: 요구 요소는 월, 일, 오전/오후 총 3개이다. 답변은 오전/오후 1개만 충족한다. 따라서 60점이다.

* 문항: "오늘이 며칠인지, 그리고 며칠 뒤가 주말인지 말씀해 주세요."
  답변: "오늘 사일인데, 이틀 뒤가 주말이야"
  판단: 요구 요소는 오늘 며칠, 주말까지 남은 날 수 총 2개이다. 답변은 2개를 모두 충족한다. 따라서 100점이다.

* 문항: "지금 몇 년, 몇 월, 며칠, 무슨 요일인지 말씀해 주세요."
  답변: "몰라"
  판단: 시간·날짜 정보를 제공하지 않았다. 따라서 0점이다.

[출력]
0, 40, 60, 80, 100 중 숫자 하나만 출력한다. 다른 텍스트·기호·설명·코드펜스를 절대 붙이지 않는다.
""",

    "그림 설명하기": """
당신은 노인 인지검사의 화행 적절성 채점자다. 아래 문항에 대한 수급자의 음성 답변(STT 변환 텍스트)을 평가한다.

[이 유형의 문항 의도]
화면에 제시된 그림을 보고 그 상황을 설명하는 발화 능력 확인. 수급자가 그림 속 사물·인물·행위·장면을 언어로 묘사하도록 요구하는 문항이다.
이 평가는 그림을 얼마나 완벽하게 자세히 설명했는지를 평가하는 것이 아니라, 그림 설명하기라는 말하기 행위를 문항 의도에 맞게 수행했는지를 평가한다.

[그림 설명] {image_description}
[문항] {question_text}
[답변] {stt_text}

[평가 규칙]

* 채점자는 그림을 직접 보지 못한다. 위 [그림 설명]이 그림의 실제 내용이다. 답변이 이 그림 내용과 의미상 연결되는지를 본다.
* 평가 대상은 "제시된 그림을 보고 그림 속 장면을 설명했는가"이다.
* 답변이 [그림 설명]의 모든 세부 요소를 빠짐없이 말할 필요는 없다.
* 답변이 그림 속 주요 대상, 사물, 인물, 행동, 장소, 장면 중 일부를 말하고, 그림 설명으로 자연스럽게 해석되면 긍정적으로 평가한다.
* 그림 설명에 없는 내용을 일부 덧붙였더라도, 전체적으로 그림과 관련된 설명이면 무조건 낮게 평가하지 않는다.
* 다만 답변이 매끄럽고 길어도 [그림 설명]과 전혀 다른 장면을 지어낸 경우에는 높은 점수를 줄 수 없다.
* 발음, 문법, 말투, 존댓말 여부, 문장 완성도는 평가하지 않는다.
* 고령자의 짧은 구어체 답변을 고려한다. 짧게 답해도 그림의 주요 장면을 설명하면 높은 점수를 줄 수 있다.
* 먼저 예외를 검사한다. 답변이 비었거나 침묵뿐이면 0점. 알아볼 수 없으면 0점. 그림 설명과 전혀 무관한 내용이면 0점.
* 예외가 아니면 아래 기준으로 40~100을 매긴다.
* 그림에 없는 생활 연상이나 개인 욕구는 그림 설명으로 보지 않는다.
* 답변이 그림 속 장소·사물·인물·행동과 직접 연결되지 않으면 0점으로 평가한다.
* 예를 들어 비 오는 거리 그림에서 "김치찌개 먹고 싶다", "집에 가고 싶다"처럼 그림 속 대상이나 행동을 설명하지 않는 개인 욕구는 0점이다.
* 그림 속 소재와 직접 연결되는 개인 욕구만 40점으로 볼 수 있다. 예: 도서관 그림에서 "책 읽고 싶다", 빵집 그림에서 "빵 먹고 싶다".

[점수 기준]

* 100: 그림의 주요 장면을 분명히 설명함. 그림 속 주요 인물·사물·행동·장소 중 2개 이상을 말하거나, 그림의 핵심 상황을 한 문장으로 자연스럽게 설명함. 모든 세부 요소를 빠짐없이 말할 필요는 없다.
* 80: 그림 속 일부 장면을 설명했으나 대상이나 행동이 제한적이어서 전체 장면 설명은 다소 부족함. 그래도 그림 속 인물·사물·행동 중 하나 이상을 실제 묘사로 답했으면 80점으로 평가할 수 있다.
* 60: 그림과 일치하는 장소, 사물, 인물, 분위기 중 일부만 단편적으로 말함. 장면 설명이라기보다는 짧은 관찰에 가까움.
* 40: 그림과 관련은 있으나 장면 설명이 아니라 감상, 평가, 욕구, 훈계, 일반론, 직접 발화에 가까움. 또는 그림 속 단어·장소와 약하게 관련될 뿐 실제 묘사로 보기 어려움.
* 0: 무응답, 침묵, 알아들을 수 없음, 그림과 전혀 무관한 답변.

[경계 규칙]

* 두 점수 사이가 애매하면 낮은 점수를 택한다.
* 100점은 완벽한 묘사에만 주는 점수가 아니다. 그림 설명이라는 화행을 충분히 수행했으면 100점으로 평가한다.
* 그림 속 주요 대상과 행동을 여러 개 말했으면, 세부 정보 일부가 빠져도 100점으로 평가할 수 있다.
* 하나의 대상과 하나의 행동만 말했지만 그림 설명으로 분명하면 80점 이상으로 평가한다.
* 장소만 말하거나 사물만 말하는 경우는 보통 60점으로 평가한다.
* "좋네요", "위험해 보여요", "재밌어 보여요"처럼 감상이나 평가만 있고 그림 속 대상·행동 설명이 없으면 40점으로 평가한다.
* "책 읽고 싶다", "나도 가고 싶다"처럼 그림 속 소재와 관련된 개인 욕구만 말하면 40점으로 평가한다.
* "조용히 해", "비켜요", "하지 마세요"처럼 그림 속 상황에서 할 법한 직접 발화만 있고 장면 설명이 없으면 40점으로 평가한다.
* 그림 설명과 관련된 단어가 일부 있더라도, 답변이 그림 속 장면을 묘사하지 않으면 높은 점수를 주지 않는다.
* 그림 속 대상·행동을 설명한 답변은 표현이 짧거나 어색해도 낮게 평가하지 않는다.

[출력]
0, 40, 60, 80, 100 중 숫자 하나만 출력한다. 다른 텍스트·기호·설명·코드펜스를 절대 붙이지 않는다.
""",

    "상황 질문 답하기": """
당신은 노인 인지검사의 화행 적절성 채점자다. 아래 문항에 대한 수급자의 음성 답변(STT 변환 텍스트)을 평가한다.

[이 유형의 문항 의도]
일상에서 생길 수 있는 상황을 제시하고, 그 상황에서 어떻게 행동하거나 반응할지 말하도록 요구하는 문항이다. 이 평가는 대처 방법이 실제로 옳은지, 안전한지, 문제 해결에 효과적인지를 평가하는 것이 아니다. 오직 질문이 요구한 말하기 행위에 맞게 답했는지를 평가한다.

[문항] {question_text}
[답변] {stt_text}

[평가 규칙]
- 평가 대상은 "상황 질문에 대해 자신의 행동, 대처, 반응을 답했는가"이다.
- 답변 내용이 실제로 안전한지, 올바른지, 효과적인지는 평가하지 않는다.
- 문항이 "어떻게 하겠는가", "어떻게 해야 하는가"를 묻는다면, 답변자가 그 상황에서 할 행동이나 반응을 말했는지를 본다.
- 발음, 문법, 말투, 존댓말 여부, 문장 완성도는 평가하지 않는다.
- 고령자의 짧은 구어체 답변을 고려한다. 짧게 답해도 질문에 맞는 행동이나 반응이 분명하면 높은 점수를 줄 수 있다.
- 먼저 예외를 검사한다. 답변이 비었거나 침묵뿐이면 0점. 알아볼 수 없으면 0점. 문항 상황과 전혀 무관하면 0점.
- 예외가 아니면 아래 기준으로 40~100을 매긴다.
- 회피, 포기, 거절, 무시, 그냥 가기처럼 실제 대처로는 미흡할 수 있는 답변이라도, 문항 상황에서 자신이 할 행동을 분명히 말한 경우에는 화행 적절성 자체는 높게 평가한다.
- 답변 내용의 안전성, 도덕성, 효율성, 문제 해결 가능성은 평가하지 않는다.

[점수 기준]

* 100: 문항의 핵심 상황을 이해하고, 그 상황에서 자신이 할 행동·대처·반응을 분명히 답함. 답변이 짧더라도 문항이 묻는 상황에 직접 대응하는 행동이면 100점으로 평가한다.
* 80: 문항의 핵심 상황에 대응하는 행동·대처·반응을 답했으나 표현이 짧거나 다소 막연함. 무엇을 하겠다는지는 드러나지만 구체성이 부족한 경우 80점으로 평가한다.
* 60: 문항에 나온 상황이나 단어와 관련은 있으나, 문항의 핵심 상황에 대한 대처로 보기에는 불완전함. 감정·상태 표현, 단어 반응, 핵심 단어와 관련된 짧은 행동, 혼잣말성 반응처럼 질문이 요구한 행동 답변으로는 약한 경우 60점으로 평가한다.
* 40: 문항 상황과 관련은 있으나, 일반론·평가·훈계·상황 설명에 그치고 답변자 자신의 행동·대처·반응을 답하지 않음.
* 0: 무응답, 침묵, 알아들을 수 없음, 문항 상황과 전혀 무관한 답변.

[경계 규칙]

* 두 점수 사이가 애매하면 낮은 점수를 택한다.
* 답변의 안전성, 정답성, 문제 해결 효과 때문에 점수를 낮추지 않는다.
* 실제로 위험하거나 비효율적인 행동이라도, 문항의 핵심 상황에 대한 자신의 행동이나 대처를 분명히 말했으면 화행 적절성은 높게 평가한다.
* 단순 감정 표현만 있고 행동이나 대처가 없으면 60점 이하로 평가한다.
* 상황을 설명만 하고 자신이 무엇을 할지 답하지 않으면 60점 이하로 평가한다.
* 행동 동사가 있더라도, 그 행동이 문항의 핵심 상황에 대응하지 않고 문항에 나온 단어에만 반응한 수준이면 80점 이상으로 평가하지 않는다.
* 문항에 나온 핵심 단어만 반복하거나 그 단어와 관련된 짧은 행동을 말했지만, 문항 상황에 대한 대처로 해석하기 어려우면 60점으로 평가한다.
* "조심해야 한다", "도리다", "위험하다", "좋지 않다", "문제다"처럼 상황에 대한 일반론, 평가, 훈계만 있고 답변자 자신의 행동·대처·반응이 없으면 40점으로 평가한다.
* 감정이나 상태 표현은 답변자 자신의 반응이므로 60점으로 평가할 수 있지만, 일반론이나 규범적 평가는 자신의 행동·반응 답변이 아니므로 40점으로 평가한다.
* 질문이 "어떻게 하겠는가"처럼 대처 방식을 설명하도록 요구하는 경우, 답변자가 자신의 행동·대처를 설명하면 높은 점수를 준다.
다만 문항 상황과 의미상 연결되는 말을 그대로 직접 발화한 형태(예: 거스름돈 상황에서 "내 돈 내놔!", 위험 상황에서 "살려주세요!", 갈등 상황에서 "그만해!")는 문항 상황과 관련된 반응으로 볼 수 있으나, 대처를 설명한 답변으로는 다소 불완전하므로 원칙적으로 80점으로 평가한다. 문항 상황과 의미상 연결되지 않는 욕설·감탄사·공격적 발화는 이에 해당하지 않는다.
* 직접 발화라도 "도와달라고 말할 거야", "돈을 돌려달라고 할 거야"처럼 자신이 할 행동으로 설명되어 있으면 100점으로 평가한다.
- 직접 발화형 답변은 문항 상황과 의미상 연결될 때만 인정한다.
- 직접 발화형 답변은 별도로 구분한다. 답변이 "누구세요?", "살려주세요!", "조용히 좀 하세요!", "왜 연락이 없어?", "내 돈 내놔!"처럼 상황 속에서 할 말을 그대로 말한 형태이면, 문항 상황과 관련된 반응으로 인정하되 원칙적으로 80점으로 평가한다.
- 직접 발화형 답변이라도 "물어볼 거야", "말할 거야", "요청할 거야", "따질 거야", "도와달라고 할 거야"처럼 답변자 자신의 행동을 설명한 형태이면 100점으로 평가한다.
- "어떻게 하지?", "어디로 가야 하지?", "뭐였더라?", "왜 이러지?"처럼 혼잣말성 의문만 있고 실제 행동·대처가 없으면 60점으로 평가한다.
- "슬프다", "무섭다", "짜증 난다", "걱정된다"처럼 답변자 자신의 감정·상태를 직접 말하면 60점으로 평가한다.
- 그러나 상황, 세상, 사람, 사물에 대한 일반 평가·불평·훈계만 있으면 40점으로 평가한다. 예: "불은 위험하다", "요즘 세상은 무섭다", "자식 키워봤자 소용없다", "가게는 돈을 정확히 줘야 한다".
- 문항에 나온 단어를 사용했더라도, 그 답변이 문항의 핵심 상황에 대한 행동으로 자연스럽게 이어지지 않으면 높은 점수를 주지 않는다.
- 예를 들어 "물이 안 나올 때는 어떻게 하겠는가"라는 문항에서 "물 마셔"는 물이라는 단어에만 반응한 답변에 가까우므로 60점으로 평가한다.
- 반면 "물을 주문한다", "물을 사 온다", "관리실에 연락한다"처럼 물이 안 나오는 상황에서 자신이 취할 행동으로 해석되는 답변은 100점으로 평가할 수 있다.
- 욕설·비속어·공격적 표현만 있고 문항 상황과 연결되는 단어, 감정, 행동, 반응이 없으면 0점으로 평가한다.
- 욕설이 포함되어 있어도 문항 상황과 연결되는 내용이 있으면 욕설 자체는 감점하지 않고 나머지 내용으로 평가한다.
- 문항 속 대상에 대한 정의나 설명만 말한 경우는 일반론으로 보고 40점으로 평가한다.
- 예: "계좌번호는 개인정보야", "불은 위험해", "물은 중요해"처럼 문항의 핵심 단어를 설명하거나 평가만 하고 자신의 행동·반응이 없으면 40점으로 평가한다.
- 직접 발화형 답변이라도 행동 의도나 상황 반응이 불명확한 반문에 가까우면 60점으로 평가할 수 있다.


[출력]
0, 40, 60, 80, 100 중 숫자 하나만 출력한다. 다른 텍스트·기호·설명·코드펜스를 절대 붙이지 않는다.
""",

    "규칙 기반 언어추론": """
당신은 노인 인지검사의 화행 적절성 채점자다. 아래 문항에 대한 수급자의 음성 답변(STT 변환 텍스트)을 평가한다.

[이 유형의 문항 의도]
두 대상을 제시하고 둘의 공통점(공통 범주나 공유 속성)을 설명하도록 요구하는 문항이다. 두 대상을 아우르는 상위 범주를 말하는 것이 가장 적절하며, 공유하는 속성을 말하는 것도 부분적으로 타당하다.

[문항] {question_text}
[답변] {stt_text}

[평가 규칙]
- 평가 대상은 "공통점을 묻는 화행에 두 대상의 공통 범주/속성으로 응답했는가"이다. 문항에 제시된 두 대상을 함께 아우르는 답인지를 본다. 발음·문법은 평가하지 않는다.
- 먼저 예외를 검사한다. 비었거나 침묵뿐이면 0점. 알아볼 수 없으면 0점. 공통점과 전혀 무관하면 0점.
- 예외가 아니면 아래 기준으로 40~100을 매긴다.

[점수 기준]
- 100: 두 대상의 본질적인 공통점을 분명히 답함. 상위 범주, 핵심 기능, 핵심 용도 중 하나를 말하면 100점으로 평가한다.
- 80: 두 대상에 모두 해당하는 구체적 속성이나 부가적 용도를 말했으나, 상위 범주나 핵심 기능까지는 이르지 못함.
- 60: 두 대상에 모두 해당할 수는 있으나 너무 넓거나 모호해서 공통점으로서 약함.
- 40: 한쪽 대상만 설명하거나, 우연한 장소·상황만 말하거나, 공통점이 아니라 개별 특징을 말함.
- 0: 무응답, 알아들을 수 없음, 문항과 무관한 답변.

[경계 규칙]
- 반드시 정답 단어와 똑같이 말할 필요는 없다. 같은 의미의 표현이면 인정한다.
- 범주명을 직접 말하지 않아도, 두 대상의 핵심 기능이나 핵심 용도를 분명히 말하면 100점으로 평가한다.
- 단순히 둘 다 어딘가에 있을 수 있다, 사람들이 좋아한다, 흔히 본다처럼 우연적이거나 넓은 표현은 높게 평가하지 않는다.
- 한쪽 대상에만 해당하는 설명은 40점 이하로 평가한다.
- 두 점수 사이가 애매하면 낮은 점수를 택한다.

[출력] 0, 40, 60, 80, 100 중 숫자 하나만 출력한다. 다른 텍스트·기호·설명·코드펜스를 절대 붙이지 않는다.
""",

    "추억 말하기": """
당신은 노인 인지검사의 화행 적절성 채점자다. 아래 문항에 대한 수급자의 음성 답변(STT 변환 텍스트)을 평가한다.

[이 유형의 문항 의도]
과거 경험을 떠올려 자유롭게 이야기하도록 요구하는 문항이다. 정답이 없는 개방형이며, 문항이 지정한 회상 주제(음식·장소·사람·시절·가족·일 등)에 맞는 과거 경험을 진술하는지를 본다. 기억 내용의 사실 여부는 평가하지 않는다.

[문항] {question_text}
[답변] {stt_text}

[평가 규칙]

* 평가 대상은 "회상을 요구하는 화행에 해당 주제의 과거 경험 진술로 응답했는가"이다.
* 문항이 지정한 회상 주제와 답변이 맞는지, 과거 시점의 경험으로 이야기되는지를 본다.
* 발음, 문법, 말투, 존댓말 여부, 사실성은 평가하지 않는다.
* 고령자의 짧은 구어체 답변을 고려한다. 답변이 짧아도 과거 경험을 말하고 있으면 긍정적으로 평가한다.
* 먼저 예외를 검사한다. 답변이 비었거나 침묵뿐이면 0점. 알아볼 수 없으면 0점. 회상 주제와 전혀 무관하면 0점.
* 예외가 아니면 아래 기준으로 40~100을 매긴다.

[점수 기준]

* 100: 문항이 요구한 주제에 맞는 구체적 과거 경험을 이야기함. 과거 시점, 사람, 장소, 행동, 사건, 감정, 상황 중 여러 요소가 드러나며 하나의 장면처럼 이해된다.
* 80: 문항이 요구한 주제에 맞는 과거 경험을 말했으나 짧고 단편적임. 과거에 했던 일, 있었던 일, 좋아했던 것, 살았던 곳, 만났던 사람 등이 간단히 드러난다.
* 60: 주제와 관련은 있으나 회상이 매우 모호하거나, 과거 경험보다는 현재 상태·현재 감정·현재 선호에 가까움. 또는 과거와 관련된 느낌은 있으나 구체적인 경험 진술이 부족함.
* 40: 주제와 약하게 관련될 뿐, 개인의 과거 경험이 아니라 일반론·교훈·훈계·평가·상식에 가까움.
* 0: 무응답, 침묵, 알아들을 수 없음, 문항과 전혀 무관한 답변.

[경계 규칙]

* 두 점수 사이가 애매하면 낮은 점수를 택한다.
* "했어요", "있었어요", "살았어요", "다녔어요", "먹었어요", "키웠어요", "갔어요", "기억나요", "생각나요"처럼 과거 경험을 말하는 표현이 있으면 회상 답변으로 본다.
* 과거 경험이 짧게라도 드러나면 80점 이상으로 평가할 수 있다.
* "장사를 했어요", "닭을 키웠어요", "결혼식 했죠", "바다에 간 적 있어요"처럼 짧고 단편적이어도 주제에 맞는 과거 경험이면 80점으로 평가한다.
* "학교는 멀었어요", "겁이 많았죠", "형제 많았어요"처럼 과거와 관련된 상태 설명이지만 구체 사건이나 장면이 부족하면 60점으로 평가한다.
* "여행 가고 싶네요", "부모님은 소중하죠", "요즘은 잘 안 먹어요"처럼 현재 감정·현재 선호·현재 상태에 가까우면 60점으로 평가한다.
* "공부는 해야죠", "일은 다 힘들어요", "결혼은 서로 잘 살아야 해요", "운동은 몸에 좋아요", "김치는 건강에 좋아요"처럼 주제와 관련된 일반론·교훈·훈계만 있고 개인의 과거 경험이 드러나지 않으면 40점으로 평가한다.
* "동물은 귀엽죠", "명절은 즐거워요", "시장에는 먹을 게 많죠"처럼 주제 단어와 관련된 일반 평가만 있으면 40점으로 평가한다.
* 한쪽으로 주제를 넓혀 말했더라도 개인의 과거 경험이 드러나지 않으면 높은 점수를 주지 않는다.
* 답변이 문항 주제와 전혀 다른 이야기를 하면 0점으로 평가한다.

[출력]
0, 40, 60, 80, 100 중 숫자 하나만 출력한다. 다른 텍스트·기호·설명·코드펜스를 절대 붙이지 않는다.
""",
}

# 공통 프롬프트 조립 함수

def build_appropriateness_prompt(
    question_type_name,
    question_text,
    stt_text,
    image_description=None
):
    if question_type_name not in APPROPRIATENESS_PROMPTS:
        raise ValueError(f"알 수 없는 문항 유형입니다: {question_type_name}")

    if image_description is None:
        image_description = ""

    prompt = APPROPRIATENESS_PROMPTS[question_type_name]

    prompt = (
        prompt
        .replace("{question_text}", question_text)
        .replace("{stt_text}", stt_text)
        .replace("{image_description}", image_description)
    )

    return prompt

# 점수 파싱 함수

def parse_score(raw_output):
    """
    LLM 출력에서 0, 40, 60, 80, 100 중 하나만 추출한다.
    """

    text = str(raw_output).strip()

    if text.isdigit():
        score = int(text)
        if score in VALID_SCORES:
            return score

    numbers = re.findall(r"\b(?:0|40|60|80|100)\b", text)

    if len(numbers) == 1:
        score = int(numbers[0])
        if score in VALID_SCORES:
            return score

    raise ValueError(f"점수 형식이 올바르지 않습니다. LLM 출력: {raw_output}")

# 화행 적절성 채점 함수

def score_appropriateness_with_llm(
    question_type_name,
    question_text,
    stt_text,
    image_description=None
):
    """
    문항 유형, 문항, STT 답변을 바탕으로 화행 적절성 점수를 계산한다.
    반환값: 0, 40, 60, 80, 100 중 하나
    """

    if client is None:
        raise ValueError("OPENAI_API_KEY 환경변수가 설정되어 있지 않아 LLM 채점을 실행할 수 없습니다.")

    prompt = build_appropriateness_prompt(
        question_type_name=question_type_name,
        question_text=question_text,
        stt_text=stt_text,
        image_description=image_description
    )

    response = client.responses.create(
        model=LLM_MODEL_NAME,
        input=prompt,
        temperature=0,
        max_output_tokens=32,
    )

    raw_output = response.output_text.strip()
    score = parse_score(raw_output)

    return score

# 통합 채점 함수

def analyze_question_answer(
    audio_path,
    question_type_name,
    question_text,
    image_description=None,
    use_llm_scoring=True
):
    """
    음성 답변 파일 하나를 분석하여 DB 저장 및 리포트 생성에 필요한 값을 반환한다.

    audio_path: 녹음된 음성 파일 경로
    question_type_name: 문항 유형명
    question_text: 사용자에게 제시된 문항 텍스트
    image_description: 그림 설명하기 문항의 이미지 설명 기준. 다른 유형은 None.
    use_llm_scoring: 화행 적절성 LLM 채점을 실행할지 여부
    """

    # 1. 음성 파일 → STT 텍스트
    stt_text = transcribe_audio(audio_path)

    # 2. STT 텍스트 최소 전처리
    preprocessed_text = preprocess_stt_text(stt_text)

    # 3. 음성 파일 기반 반응 시간 계산
    response_time = calculate_response_time_from_audio(audio_path)

    # 4. 반복어 비율 계산
    repetition_result = analyze_repetition(preprocessed_text)

    # 5. 답변 전체 의미 글자 수 계산
    length_result = analyze_answer_length(
        preprocessed_text,
        question_type_name
    )

    # 6. 화행 적절성 LLM 채점
    if use_llm_scoring:
        appropriateness_score = score_appropriateness_with_llm(
            question_type_name=question_type_name,
            question_text=question_text,
            stt_text=preprocessed_text,
            image_description=image_description
        )
    else:
        appropriateness_score = None

    # 7. 최종 분석 결과 반환
    return {
        # QUESTION_RESULTS에 저장할 값
        "audio_file_path": str(audio_path),
        "stt_text": stt_text,
        "preprocessed_text": preprocessed_text,

        # ANALYSIS_RESULTS에 저장할 값
        "response_time": response_time,
        "repetition_ratio": repetition_result["repetition_ratio"],
        "avg_sentence_length": length_result["avg_sentence_length"],
        "appropriateness_score": appropriateness_score,

        # 리포트 계산용 보조 점수
        "repetition_score": repetition_result["repetition_score"],
        "sentence_length_score": length_result["sentence_length_score"],
    }

# 리포트 요약 함수

def calculate_average(values):
    """
    None을 제외하고 평균을 계산한다.
    값이 없으면 None을 반환한다.
    """

    valid_values = [
        value for value in values
        if value is not None
    ]

    if len(valid_values) == 0:
        return None

    return round(sum(valid_values) / len(valid_values), 2)


def score_response_time(response_time):
    """
    반응 시간을 0~100점으로 변환한다.
    단위: 초
    """

    if response_time is None:
        return 0

    if response_time <= 3:
        return 100
    elif response_time <= 5:
        return 80
    elif response_time <= 8:
        return 60
    elif response_time <= 12:
        return 40
    else:
        return 0
    
# 문항/항목별 가중치

QUESTION_TYPE_WEIGHTS = {
    "오늘 날짜 말하기": {
        "appropriateness": 0.70,
        "response_time": 0.20,
        "repetition": 0.10,
        "answer_length": 0.00,
    },
    "그림 설명하기": {
        "appropriateness": 0.60,
        "response_time": 0.10,
        "repetition": 0.10,
        "answer_length": 0.20,
    },
    "상황 질문 답하기": {
        "appropriateness": 0.70,
        "response_time": 0.10,
        "repetition": 0.10,
        "answer_length": 0.10,
    },
    "규칙 기반 언어추론": {
        "appropriateness": 0.75,
        "response_time": 0.10,
        "repetition": 0.10,
        "answer_length": 0.05,
    },
    "추억 말하기": {
        "appropriateness": 0.60,
        "response_time": 0.05,
        "repetition": 0.10,
        "answer_length": 0.25,
    },
}


def calculate_question_final_score(row):
    """
    문항 하나의 지표별 점수와 종합 점수를 계산한다.
    """

    question_type_name = row["question_type_name"]

    appropriateness_score = row.get("appropriateness_score")
    if appropriateness_score is None:
        appropriateness_score = 0

    response_time_score = score_response_time(
        row.get("response_time")
    )

    repetition_score = score_repetition_ratio(
        row.get("repetition_ratio")
    )

    answer_length_score = score_answer_length(
        row.get("avg_sentence_length"),
        question_type_name
    )

    weights = QUESTION_TYPE_WEIGHTS.get(question_type_name)

    if weights is None:
        raise ValueError(f"알 수 없는 문항 유형입니다: {question_type_name}")

    final_score = (
        appropriateness_score * weights["appropriateness"]
        + response_time_score * weights["response_time"]
        + repetition_score * weights["repetition"]
        + answer_length_score * weights["answer_length"]
    )

    return {
        **row,
        "response_time_score": response_time_score,
        "repetition_score": repetition_score,
        "answer_length_score": answer_length_score,
        "final_score": round(final_score, 2),
    }

# 리포트 요약 함수 추가

def calculate_question_type_summaries(scored_rows):
    """
    문항 유형별 평균값을 계산한다.
    """

    grouped = {}

    for row in scored_rows:
        question_type_name = row["question_type_name"]

        if question_type_name not in grouped:
            grouped[question_type_name] = []

        grouped[question_type_name].append(row)

    summaries = {}

    for question_type_name, rows in grouped.items():
        summaries[question_type_name] = {
            "question_count": len(rows),
            "avg_response_time": calculate_average([row["response_time"] for row in rows]),
            "avg_repetition_ratio": calculate_average([row["repetition_ratio"] for row in rows]),
            "avg_sentence_length": calculate_average([row["avg_sentence_length"] for row in rows]),
            "avg_appropriateness_score": calculate_average([row["appropriateness_score"] for row in rows]),
            "avg_response_time_score": calculate_average([row["response_time_score"] for row in rows]),
            "avg_repetition_score": calculate_average([row["repetition_score"] for row in rows]),
            "avg_answer_length_score": calculate_average([row["answer_length_score"] for row in rows]),
            "avg_final_score": calculate_average([row["final_score"] for row in rows]),
        }

    return summaries


def calculate_report_summary(analysis_rows):
    """
    여러 문항의 분석 결과를 받아 리포트용 요약값을 만든다.

    analysis_rows에는 각 row마다 question_type_name이 포함되어 있어야 한다.
    """

    if analysis_rows is None or len(analysis_rows) == 0:
        return {
            "question_count": 0,
            "avg_response_time": None,
            "avg_repetition_ratio": None,
            "avg_sentence_length": None,
            "avg_appropriateness_score": None,
            "avg_response_time_score": None,
            "avg_repetition_score": None,
            "avg_answer_length_score": None,
            "avg_final_score": None,
            "question_type_summaries": {},
            "rows": [],
        }

    scored_rows = [
        calculate_question_final_score(row)
        for row in analysis_rows
    ]

    return {
        "question_count": len(scored_rows),

        "avg_response_time": calculate_average([row["response_time"] for row in scored_rows]),
        "avg_repetition_ratio": calculate_average([row["repetition_ratio"] for row in scored_rows]),
        "avg_sentence_length": calculate_average([row["avg_sentence_length"] for row in scored_rows]),
        "avg_appropriateness_score": calculate_average([row["appropriateness_score"] for row in scored_rows]),

        "avg_response_time_score": calculate_average([row["response_time_score"] for row in scored_rows]),
        "avg_repetition_score": calculate_average([row["repetition_score"] for row in scored_rows]),
        "avg_answer_length_score": calculate_average([row["answer_length_score"] for row in scored_rows]),
        "avg_final_score": calculate_average([row["final_score"] for row in scored_rows]),

        "question_type_summaries": calculate_question_type_summaries(scored_rows),
        "rows": scored_rows,
    }